### ISSUE TITLE
Setup Github integration with Heroku

### ISSUE THREAD

**Issue by nerner-code** [PythonGurl/Dashboard#23]
We want to have Heroku auto-deploy the app from main once you push to Github.
[This article](https://medium.com/featurepreneur/how-to-connect-github-to-heroku-be6ff27419d3) may be helpful as a starting point.

**Comment by PythonGurl** [comment]
https://python-gurl-dash-app.herokuapp.com/

**Comment by nerner-code** [comment]
In order to check that Github integration worked, you could change `hello world` to saying something else and then see if merging to main auto-deploys.

**Comment by PythonGurl** [comment]
it works. 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/99092545/192115200-cd8915b2-67df-4874-8a90-be2547b07bb5.png">
