### ISSUE TITLE
Update the tab for your website to have a more descriptive name than Dash

### ISSUE THREAD

**Issue by nerner-code** [PythonGurl/Dashboard#24]
<img width="244" alt="image" src="https://user-images.githubusercontent.com/10356243/191404174-ceadcaa6-bd45-4451-ae31-e419a35e6fae.png">
 
[This post](https://community.plotly.com/t/change-the-title-in-tab/9505) has some pointers.

**Comment by PythonGurl** [comment]
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/99092545/192115569-043e7875-f736-431f-83e9-c9e6d72072fe.png">
