### ISSUE TITLE
dash base app

### ISSUE THREAD

**Issue by nerner-code** [PythonGurl/Dashboard#5]
We want to have a plotly dash app to display the data in this repo.

Let's go ahead and copy the dash app [here](https://dash.plotly.com/deployment) in `app.py` as a starting point and get that working locally on a branch.  Once that is working, please submit a PR with a screenshot of the local webpage for review.

**Comment by PythonGurl** [comment]
How do I create Procfile and requirements.txt
<img width="656" alt="image" src="https://user-images.githubusercontent.com/99092545/186563877-316152bd-f504-486e-a236-f322023aa1bc.png">

**Comment by nerner-code** [comment]
Feel free to ignore those steps for now.  We will deploy to heroku later.  For this change, all we need to do is get a plotly dash app working locally.

**Comment by PythonGurl** [comment]
I've installed Dash under my env/bin/python
However, I got this error when trying to run app.py.  It looks like app.py is not running under my env/bin/python. How do I change it?

![image](https://user-images.githubusercontent.com/99092545/186564608-ca848cca-b3b7-489e-90c7-a4faa2f25fbf.png)

**Comment by nerner-code** [comment]
It looks like VS Code is currently using the interpreter at `/opt/homebrew/bin/python3`, but we want to use the interpreter at `env/bin/python`.  You should be able to update the interpreter used by VS Code by following the instructions [here](https://stackoverflow.com/questions/47602151/how-to-change-interpreter-in-visual-studio-code).

**Comment by PythonGurl** [comment]
It works. 
![image](https://user-images.githubusercontent.com/99092545/186566081-5bdcde85-b86e-4b3d-9c91-cba72d8c4f45.png)

Question: how do I terminate the running? 3Q
![image](https://user-images.githubusercontent.com/99092545/186566199-0c55b3a6-cd3c-48e4-9b3c-b1ec80825421.png)

**Comment by nerner-code** [comment]
Nice, you should be able to click on the terminal running the server and press `ctrl + c` to stop the server.
